table data
	lineageTag: 631cdf92-b5d0-43be-bbb6-98fe6c4d06a1

	column Catergry
		dataType: string
		lineageTag: cda0ec36-a8e8-4824-8ebe-708d361a8224
		summarizeBy: none
		sourceColumn: Catergry

		annotation SummarizationSetBy = Automatic

	column 'Sum of Quantity'
		dataType: int64
		formatString: 0
		lineageTag: a28c1f92-71e1-4c5d-ba2a-25eeca4d0c77
		summarizeBy: sum
		sourceColumn: Sum of Quantity

		annotation SummarizationSetBy = Automatic

	column 'Order value '
		dataType: int64
		formatString: 0
		lineageTag: dd9fdf28-19e2-488e-b419-d46a51c3b320
		summarizeBy: sum
		sourceColumn: "Order value "

		annotation SummarizationSetBy = Automatic

	column Rankx
		dataType: int64
		formatString: 0
		lineageTag: 59a79bba-c1d7-4699-baf7-47960bf1528d
		summarizeBy: sum
		sourceColumn: Rankx

		annotation SummarizationSetBy = Automatic

	column SUMX
		dataType: int64
		formatString: 0
		lineageTag: 855051db-b217-4430-90e0-ffc8b8d155c4
		summarizeBy: sum
		sourceColumn: SUMX

		annotation SummarizationSetBy = Automatic

	partition data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\JAJAV1\OneDrive - IKEA\Desktop\Book1.xlsx"), null, true),
				    data_Sheet = Source{[Item="data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Catergry", type text}, {"Sum of Quantity", Int64.Type}, {"Order value ", Int64.Type}, {"Rankx", Int64.Type}, {"SUMX", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

